<Project Sdk="MSTest.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<EnableTrimAnalyzer>false</EnableTrimAnalyzer>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="Repl.Testing" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yllibed.TenantCloudClient\Yllibed.TenantCloudClient.csproj" />
		<ProjectReference Include="..\Yllibed.TenantCloudClient.Cdp\Yllibed.TenantCloudClient.Cdp.csproj" />
		<ProjectReference Include="..\Yllibed.TenantCloudClient.Mcp\Yllibed.TenantCloudClient.Mcp.csproj" />
	</ItemGroup>

</Project>
