<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<!-- XML docs will be added incrementally -->
		<NoWarn>CS1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Yllibed.TenantCloudClient</PackageId>
		<Authors>Carl de Billy</Authors>
		<Company>Yllibed project</Company>
		<Product>Tenant Cloud API Client Library</Product>
		<Description>
			This client library will reach the TenantCloud undocumented API to extract some useful information.

			** THIS IS NOT AN OFFICIAL API CLIENT FOR TENANTCLOUD ** (anyway there's no such thing as an official API yet)
		</Description>
		<Copyright>Copyright (C) 2019-$([System.DateTime]::Now.Year) - Carl de Billy - All Rights Reserved</Copyright>
		<PackageProjectUrl>https://github.com/yllibed/TenantCloudClient</PackageProjectUrl>
		<RepositoryUrl>https://github.com/yllibed/TenantCloudClient</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>tenantcloud</PackageTags>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Yllibed.TenantCloudClient.Tests" />
	</ItemGroup>

</Project>
